sudo: required
services: 
  - docker

before_install:
  - docker build -t varshitha/react_docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true varshitha/react_docker-react npm run test -- --coverage

after_success:
  - docker build -t 1sonudocker/multi-client ./client
  - docker build -t 1sonudocker/multi-nginx ./nginx
  - docker build -t 1sonudocker/multi-server ./server
  - docker build -t 1sonudocker/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 1sonudocker/multi-client
  - docker push 1sonudocker/multi-nginx 
  - docker push 1sonudocker/multi-server
  - docker push 1sonudocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "complex-multi-container"
  env: "Complex-multi-container-env"
  bucket_name: "elasticbeanstalk-eu-north-1-576622836112"
  bucket_path: "docker-MULTI"
  on:
   branch: master
aws_access_key: $AWS_ACCESS_KEY_ID
aws_secret_key: 
  secure: $AWS_SECRET_ACCESS_KEY